config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
      resources :users

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :recordings
  resources :discussions do
    resources :comments
  end
end

app/models/recording.rb
class Recording < ApplicationRecord
  has_one_attached :audio_file
  after_commit :convert_to_mp3
  after_commit :get_duration, on: :create

  validates :title, presence: true
  validate :correct_mime_type

  def convertable?
    audio_file.attached? && ( (audio_file.audio? && audio_file.content_type != 'audio/mpeg') || audio_file.video? )
  end
  
  def playable?
    audio_file.attached? && audio_file.content_type == 'audio/mpeg'
  end

  def duration_formatted
    Time.at(duration.to_i).strftime("%M:%S")
  end

  private
    def convert_to_mp3
      ConvertToMp3Job.perform_later(id) if convertable?
    end

    def get_duration
      GetAudioDurationJob.perform_later(id)
    end
    
    def correct_mime_type
      if audio_file.attached? && !audio_file.audio?
        errors.add(:audio_file, 'Must be an audio file')
      end
    end

end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_recording, only: [:show, :edit, :update, :destroy]

  def index
    @recordings = Recording.all
  end

  def show
  end

  def new
    @recording = Recording.new
  end

  def create
    @recording = Recording.create(recording_params)
    
    if @recording.valid?
      flash[:success] = "Added recording"
      redirect_to recordings_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @recording.update(recording_params)
      flash[:success] = "Updated recording"
      redirect_to recording_path(Current.band, @recording)
    else
      flash[:alert] = "Could not update recording."
      render 'edit'
    end
  end

  private
    def set_recording
      @recording = Recording.find(params[:id])
    end

    def recording_params
      defaults = { }
      params.require(:recording).permit(:title, :audio_file).reverse_merge(defaults)
    end
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/views/recordings/_recording.html.erb
<% cache ['v1', recording] do %>
  <tr>
    <td><%= link_to recording.title, recording_path(recording) %></td>
    <td><%= recording.duration_formatted %></td>
  </tr>
<% end %>

app/views/recordings/index.html.erb
<h1>Recordings</h1>

<% if user_signed_in? %>
  <p><%= link_to 'New', new_recording_path, class: 'btn btn-primary' %></p>
<% end %>

<table class="table table-striped">
  <thead>
    <th>Subject</th>
    <th>Duration</th>
  </thead>
  <tbody>
    <% cache ['v1', @recordings] do %>
      <% if @recordings.any? %>
        <% @recordings.each do |recording| %>
          <%= render recording %>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/recordings/new.html.erb
<h1>Upload recording</h1>

<%= form_with model: @recording, url: [:recordings], data: { remote: false } do |form| %>
  <div class="col-lg-12 col-sm-12">
    <div class="form-group">
      <%= form.label :title, 'Title' %>
      <%= form.text_field :title, class: 'form-control' %>
      <%= error_message_on form.object, :title %>
    </div>
    
    <div class="form-group">
      <%= form.label :audio_file, 'Upload audio file' %>
      <%= form.file_field :audio_file, class: 'form-control' %>
      <%= error_message_on form.object, :audio_file %>
    </div>
  </div>


  <div class="form-group">
    <%= form.submit 'Save', class: 'btn btn-primary', data: { disable_with: 'Saving...' } %>
    <%= link_to 'Cancel', root_path(), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/recordings/show.html.erb
<h1>Recording: <%= @recording.title %> (<%= @recording.duration_formatted %>)</h1>

<% if @recording.playable? %>
  <audio id="recording_<%= @recording.id.to_s %>" controls 
    src="<%= url_for(@recording.audio_file) %>" type="audio/mpeg">
    Your browser does not support the audio element.</audio>
<% else %>
  Could not play file. Please wait a moment as we're trying to make it playable.
  <%= link_to 'Reload', recording_path(@recording) %>
<% end %>