config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
      resources :users

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :recordings
  resources :discussions do
    resources :comments
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recordings = Recording.limit(5)
  end

  def terms
  end

  def privacy
  end
end

app/views/home/index.html.erb
<h1>Recordings</h1>

<table class="table table-striped">
  <thead>
    <th>Subject</th>
    <th>Duration</th>
  </thead>
  <tbody>
    <% if @recordings.any? %>
      <% @recordings.each do |recording| %>
        <%= render recording %>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to 'More recordings...', recordings_path, class: 'btn btn-primary' %>

app/views/home/privacy.html.erb
<h1>Privacy Policy</h1>
<p class="lead">Use this for your Privacy Policy</p>

app/views/home/terms.html.erb
<h1>Terms of Service</h1>
<p class="lead">Use this for your Terms of Service</p>